[urgency_low]
    background = "#6581A380"
    foreground = "#CCE3FFE6"
    frame_color = "#6581A303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A5F6B80"
    foreground = "#CCF2FFE6"
    frame_color = "#3A5F6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5