$MOD = SUPER
$mainMod = $MOD

$TERMINAL = $(vyle -c -r TERMINAL)
$EDITOR = $(vyle -c -r EDITOR)
$EXPLORER = $(vyle -c -r EXPLORER)
$BROWSER = $(vyle -c -r BROWSER)
$LOCKSCREEN = $(vyle -c -r LOCKSCREEN)
$TASKMANAGER = $(vyle -c -r TASKMANAGER)

