$MOD = SUPER
$mainMod = $MOD

# DO NOT TOUCH THIS VARS! They essentially loads your configuration.
$TERMINAL = $(vyle -c -r TERMINAL)
$EDITOR = $(vyle -c -r EDITOR)
$EXPLORER = $(vyle -c -r EXPLORER)
$BROWSER = $(vyle -c -r BROWSER)
$LOCKSCREEN = $(vyle -c -r LOCKSCREEN)
$TASKMANAGER = $(vyle -c -r TASKMANAGER)
$CURSOR = $(vyle -c -r CURSOR)
$CURSOR_SIZE = $(vyle -c -r CURSOR_SIZE)
