#!/usr/bin/env bash
wallSet="/home/iris/.config/ivy-shell/theme/Decay-Green/wallpapers/blue_swirl.png"
wallDir="${XDG_CONFIG_HOME:-$HOME/.config}/ivy-shell/theme/Decay-Green/wallpapers"
enableWallIde=0
VYLE_THEME="Wallbash-Ivy"
VYLE_RESERVED_THEME="Decay-Green"

