#!/usr/bin/env bash
set -eo pipefail

scrDir="$HOME/.local/bin"
source "${scrDir}/globalcontrol.sh"

PrevStoreVyle="${PrevThemeIde}"

[[ ! -f "${scrDir}/themeswitch.sh" ]] && echo -e " Vyle-Project - ERROR! Does themeswitch.sh exist!?" && exit 1
[[ ! -f "${scrDir}/wbselecgen.sh" ]] && echo -e " Vyle-Project - ERROR! Does wbselecgen.sh exists!?" && exit 1

print_usage() {
  local pr_usage="$1"
  print_use() {
    echo -e "Vyle-Project's Official Command-line interface."
    echo -e "Usage:
    vyle [flags]"
    
    echo -e "Available Flags: 
    theme         Manage themes
    config        write config
    wallpaper     Manage wallpapers
    dispatch      Dispatch Scripts
    reload        Reload Vyle
    init          Initialize Sourcing"
    
    echo -e "Tips: 
    Use $(basename "$0") [command] --help for more information about a command."
    exit 0
  }

  print_theme() {
    echo -e "Vyle-Project: Manage theme including selecting, navigating and listing available themes."
              
    echo -e "Usage:
    $(basename "$0") theme [flags]"

    echo -e "Available Flags:
    next   | -n    Switch to the next theme
    prev   | -p    Switch to the previous theme
    select | -s    Select a theme
    set    | -se   Set a theme using the specified theme name
    list   | -le   List available themes
    debug  | -d    [Flags: -n, -p, -s, -se], Shows debug update"
    exit 0
  }

  print_conf() {
    echo -e "Vyle-Project: Write, Read or Inspect raw configuration."
    echo -e "Usage:
    $(basename "$0") config [Flags] [Subflags] [Paths] [Group] [Key] [Value]"

    echo -e "Available Flags:
    write   | -w    Write to a config file. Usage: \"vyle -c -w\" \"ideTheme\" \"Catppuccin-Mocha\" \"ide.conf\"
    read    | -r    Read a Variable from ${ideDir}/ide.conf
    raw     | -raw  Read the raw file of ide.conf
    toml    | -t    Read or write to specified toml file. 
            Example: $(basename "$0") -c -t [Flags: -r -t] [Path] [Group] [Key] [Value]
                     $(basename "$0") -c -t -r ./vyle.toml \"Rofi.Wallbash\" \"Scale\"
                     $(basename "$0") -c -t -w ./vyle.toml \"Rofi.Wallbash\" \"Scale\" \"10\""
    exit 0
  }

  print_wall() {
    echo -e "Vyle-Project - Manage wallpapers"
    echo -e "Usage:
    $(basename "$0") wallpaper [flags]"

    echo -e "Available Flags:
    get    | -g    Get the current-wallpaper set
    list   | -l    List wallpapers. Optionally required specified directory
    next   | -n    Set the next wallpaper
    prev   | -p    Set the previous wallpaper
    random | -r    Set the random wallpaper
    select | -s    Select wallpaper using rofi
    set    | -se   Set specified wallpaper"
    echo -e "Extra-Flags:
    -h, --help     help for wallpaper"
    exit 0
  }
  
  print_dispatch() {
    echo -e "Vyle-Project - List of Scripts executable."
    echo -e "Usage:
    $(basename "$0") dispatch [script] [flags]"
    command ls "${scrDir}"
    exit 0
  }

  case "${pr_usage}" in
    -pt)
      print_theme ;;
    -pc)
      print_conf ;;
    -pw)
      print_wall ;;
    -pd)
      print_dispatch ;;
    -pu|*)
      print_use ;;
  esac
}

reload_vyle() {
  vylePrint() { 
    echo -e "Vyle-Project :: ERROR! Does $1 exists!?"
  }

  [[ ! -f "${scrDir}/logoutlaunch.sh" ]] && vylePrint "logoutlaunch.sh"
  [[ ! -f "${scrDir}/ivy-shell.sh" ]] && vylePrint "ivy-shell.sh"
  [[ ! -f "${scrDir}/swwwallcache.sh" ]] && vylePrint "swwwallcache.sh"
  [[ ! -f "${scrDir}/wallbashtoggle.sh" ]] && vylePrint "wallbashtoggle.sh"

  colorScheme="$(grep "^[[:space:]]*\$COLOR[-_]SCHEME\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface color-scheme | sed "s/'//g; s/.*-//g" \
    || { echo "colorScheme is empty!"; colorScheme="dark"; } )"
  cursorSize="$(grep "^[[:space:]]*\$CURSOR[-_]SIZE\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface cursor-size \
    || { echo "cursor-size is empty!"; cursorSize=20; } )"

  cursorTheme=$(grep "^[[:space:]]*\$CURSOR[-_]THEME\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface cursor-theme | sed "s/'//g " \
    || echo "cursorTheme is empty!" )

  gtkTheme=$(grep "^[[:space:]]*\$GTK[-_]THEME\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g" \
    || echo "gtkTheme is empty!" )

  iconTheme=$(grep "^[[:space:]]*\$ICON[-_]THEME\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g" \
    || echo "iconTheme is empty!" )

  fontName=$(grep "^[[:space:]]*\$FONT[-_]NAME\s*=" "${ideDir}/theme/${PrevThemeIde}/hypr.theme" | sed "s/^.*[[:space:]]=[[:space:]]//g; s/'//g" \
    || gsettings get org.gnome.desktop.interface font-name | sed "s/'//g" \
    || echo "fontName is empty!" )
  
  if ! gsettings set org.gnome.desktop.interface color-scheme "${colorScheme}"; then
    echo -e " :: Vyle-Project :: Failed to set ColorScheme."
  fi
  if ! gsettings set org.gnome.desktop.interface cursor-size "${cursorSize}"; then
    echo -e " :: Vyle-Project :: Failed to set CursorSize."
  fi

  if [[ -n "${cursorTheme}" ]]; then
    if ! gsettings set org.gnome.desktop.interface cursor-theme "${cursorTheme}"; then
      echo -e " :: Vyle Project :: Failed to set CursorTheme."
    fi
  fi

  if [[ -n "${gtkTheme}" ]]; then
    if ! gsettings set org.gnome.desktop.interface gtk-theme "${gtkTheme}"; then
      echo -e " :: Vyle-Project :: Failed to set GtkTheme."
    fi
  else
    if env_pkg -- -Q adw-gtk-theme >/dev/null; then
      gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk-${dcolMode}"
      gtkTheme="adw-gtk-${dcolMode}"
    fi
  fi

  if [[ -n "${iconTheme}" ]]; then
    if ! gsettings set org.gnome.desktop.interface icon-theme "${iconTheme}"; then
      echo -e " :: Vyle-Project :: Failed to set IconTheme."
    fi
  fi

  if [[ -n "${fontName}" ]]; then
    if ! gsettings set org.gnome.desktop.interface font-name "${fontName}"; then
      echo -e " :: Vyle-Project :: Failed to set FontSchema."
    fi
  fi

  if [[ "$(srcf_rcall setConf)" -ge 1 ]]; then
    echo " :: Vyle-Project :: function {setConf} does NOT exist!"
    setConf() {
      set +H
      local varString="${1}"
      local varValue="${2}"
      local varPath="${3}"

      [[ -z "${varValue}" ]] && { echo -e " :: Vyle-Project :: NO value has been passed!"; return 1; }
      local IFS="|!"
      read -ra confStrings <<<"${varString}"
      read -ra confValue <<< "${varValue}"

      for i in "${!confStrings[@]}"; do
        local confKey="${confStrings[i]}"
        local confVal="${confValue[i]}"
        [[ "${confVal}" =~ ^[0-9]+$ ]] || confVal="\"${confVal}\""
        [[ "$(grep -c "^${confKey}" "${varPath}" 2>/dev/null)" -eq 1 ]] && sed -i "s|^${confKey}=.*|${confKey}=${confVal}|" "${varPath}" || echo "${confKey}=${confVal}" >> "${varPath}"
      done
      set -H
    }
  fi

  TERM="$(echo "${TERMINAL}" | sed "s/[[:space:]][-_][A-Za-z]//g")"
  setConf "icon_theme" "${iconTheme}" "${confDir}/qt6ct/qt6ct.conf"
  setConf "Theme" "${iconTheme}" "${confDir}/kdeglobals.conf"
  [[ -z "${TERM}" ]] || setConf "TerminalApplication" "${TERM}" "${confDir}/kdeglobals"
  setConf "ColorScheme" "colors" "${confDir}/kdeglobals"
  setConf "widgetStyle" "kvantum" "${confDir}/kdeglobals"
  setConf "Inherits" "${cursorTheme}" "$HOME/.icons/default/index.theme"
  setConf "gtk-theme-name" "${gtkTheme}" "${confDir}/gtk-3.0/settings.ini"
  setConf "gtk-icon-theme-name" "${iconTheme}" "${confDir}/gtk-3.0/settings.ini"
  setConf "gtk-cursor-theme-name" "${cursorTheme}" "${confDir}/gtk-3.0/settings.ini"

  "${scrDir}/wbselecgen.sh" -t s >/dev/null
}

initialized() {
  cat <<EOF
VYLE_SHELL_INIT=1
scrDir="${scrDir}"
export scrDir VYLE_SHELL_INIT
EOF
    cat "${scrDir}/globalcontrol.sh"
}

case "${1}" in
  theme | -t) 
    case "${2}" in
      next | -n)
        "${scrDir}/themeswitch.sh" -n >/dev/null 2>&1
        ;;
      prev | -p | previous)
        "${scrDir}/themeswitch.sh" -p >/dev/null 2>&1
        ;;
      select | -s)
        "${scrDir}/themeswitch.sh" >/dev/null 2>&1
        ;;
      set | -se)
        "${scrDir}/themeswitch.sh" -t "${3}" >/dev/null 2>&1 
        ;;
      list | -le)
        theme=$(find "${ideDir}/theme" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort -Vf)

        while read -r thmPath; do
          thmList+=("${thmPath}")
        done <<< "${theme}"

        for indx in ${!thmList[@]}; do
          echo -e "Vyle-Project :: \${thmList[${indx}]}=\"${thmList[$indx]}\""
        done

        exit 0
        ;;
      debug | -d)
        case "${3}" in
          -n|next|-p|previous|prev|-s|select|-se|set|*)
            if [[ "${3}" == "-s" || "${3}" == "select" ]]; then
              "${scrDir}/themeswitch.sh" 
            elif [[ "${3}" == "-n" || "${3}" == "next" ]]; then
              "${scrDir}/themeswitch.sh" -n
            elif [[ "${3}" == "-p" || "${3}" == "previous" || "${3}" == "prev" ]]; then
              "${scrDir}/themeswitch.sh" -p
            elif [[ "${3}" == "-se" || "${3}" == "set" ]]; then
              "${scrDir}/themeswitch.sh" -t "${4}"
            elif [[ -z "${3}" ]]; then
              print_usage -pt
            fi
            ;;
        esac
        ;;
      --help | -h | help | *)
        print_usage -pt
        ;;
    esac
    ;;
  config | -c)
    case "${2}" in
      --write | write | -w)
        setConf "${3}" "${4}" "${5}"
        [[ $? -eq 0 ]] && echo -e "Vyle-Project: Configuration has been written to ${5}" || echo -e "Vyle-Project: Failed to write the configuration to ${6}"
        exit "$?"
        ;;
      --read | read | -r)
        [[ -z "${3}" ]] && { echo -e " No variable specified."; exit 1; }
        printf '%s\n' "${!3}"
        ;;
      -raw | raw)
        cat "${ideDir}/ide.conf"
        exit "$?"
        ;;
      --toml | toml | -t)
        case "${3}" in
          -r | read | --read)
            tomlq -o "${4}" "${5}" "${6}" 
            ;;
          -w | write | --write)
            tomlq -i "${4}" "${5}" "${6}" "${7}"
            if [[ $? -eq 0 ]]; then
              echo -e "Vyle-Project: \"[.${5}.${6}] = ${7}\" has been written to ${4}"
              exit 0
            else
              echo -e "Vyle-Project: Failed to write \"[.${5}.${6}]\ = \"${7}\"\" to ${4}"
              exit 1
            fi
            ;;
          -e | export | --export)
            tomlq -e
            ;;
          *)
            print_usage -pc
            ;;
        esac
        ;;
      *)
        print_usage -pc
        ;;
    esac
    ;;
  wallpaper | -w) 
    case "${2}" in
      --get | -g | get)
        echo "Vyle-Project: Current-wallpaper \"$(fl_wallpaper -r)\"
              Backened used: swww"
        exit "$?"
        ;;
      --list | -l | list)
        [[ -z "${3}" ]] && wallpaper="${ideDir}/theme" || wallpaper="${3}"
        Map=$(find "${wallpaper}" -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort -Vf)
        while read -r walls; do
          wallList+=("${walls}")
        done <<< "${Map}"

        for indx in "${!wallList[@]}"; do
          echo " Vyle-Project :: \${wallList[${indx}]}=\"${wallList[indx]}\""
        done
        ;;
      --prev | -p | prev)
        "${scrDir}/wbselecgen.sh" -p >/dev/null 
        ;;
      --next | -n | next)
        "${scrDir}/wbselecgen.sh" -n >/dev/null
        ;;
      --random | -r | random)
        "${scrDir}/wbselecgen.sh" -r >/dev/null
        ;;
      --select | -s | select)
        "${scrDir}/wbselecgen.sh" >/dev/null
        ;;
      --set | -se | set)
        "${scrDir}/wbselecgen.sh" -t "${3}" >/dev/null
        ;;
      --debug | -d)
        case "${3}" in
          --get | -g | get)
            echo "Vyle-Project: Current-wallpaper \"$(fl_wallpaper -r)\"
                  Backened used: swww"
            exit "$?"
            ;;
          --list | -l | list)
            [[ -z "${3}" ]] && wallpaper="${ideDir}/theme" || wallpaper="${3}"
            Map=$(find "${wallpaper}" "$@" -type f \( -iname "*.gif" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort -Vf)
            while read -r walls; do
              wallList+=("${walls}")
            done <<< "${Map}"

            for indx in "${!wallList[@]}"; do
              echo "Vyle-Project - \${wallList[${indx}]}=\"${wallList[indx]}\""
            done
            ;;
          --prev | -p | prev | --next | -n | next | --random | -r | random | --select | -s | select | --set | -se | set)
            if [[ "${3}" == "--prev" || "${3}" == "-p" || "${3}" == "prev" ]]; then
              "${scrDir}/wbselecgen.sh" -p
            elif [[ "${3}" == "--next" || "${3}" == "-n" || "${3}" == "next" ]]; then
              "${scrDir}/wbselecgen.sh" -n
            elif [[ "${3}" == "--random" || "${3}" == "-r" || "${3}" == "random" ]]; then
              "${scrDir}/wbselecgen.sh" -r
            elif [[ "${3}" == "--select" || "${3}" == "-s" || "${3}" == "select" ]]; then
              "${scrDir}/wbselecgen.sh"
            elif [[ "${3}" == "--set" || "${3}" == "-se" || "${3}" == "set" ]]; then
              "${scrDir}/wbselecgen.sh" -t "${4}"
            else
              print_usage -pw
            fi
            ;;
        esac
        ;;
      * | --help | -h)
        print_usage -pw
        ;;
    esac
    ;;
  --dispatch | -d | dispatch)
    shift
    [[ -z "${1}" ]] && { echo "Vyle-Project :: No Command or script path has been given. Use --get-list-help for more information." ; exit 1 ;}
    case "${1}" in
      --get-list-help | -gl | get-list-help | -h | --help | help)
        print_usage -pd
        ;;
      *)
        target="${1}"
        shift
        if [[ -x "${scrDir}/${target}" ]]; then
          "${scrDir}/${target}" "${@}"
        else
          "${target}" "${@}"
        fi 
        [[ $? -eq 1 ]] && echo -e "Vyle-Project :: Exit-Code $?"
        ;;
    esac
    ;;
  --reload | -r | reload)
    reload_vyle
    ;;
  --init | -i | init)
    initialized
    ;;
  *)
    print_usage -pu
    ;;
esac

