
#//---ivy mode enabled---
# Overriding the values below - DO NOT OVERWRITE --- # IF YOU DO, THEN EDIT $(confDir)/ivy-shell/shell/hypr.ivy-- #
general {
    col.active_border = rgba(485263ff) rgba(293852ff) 45deg
    col.inactive_border = rgba(082731ff) rgba(164859ff) 45deg
}

group {
    col.border_active = rgba(485263ff) rgba(293852ff) 45deg
    col.border_inactive = rgba(082731cc) rgba(164859cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}

decoration {
    shadow:color = rgba(082731cc)
}

#//---------------------------