
$text_color = rgba(FFFFFFFF)
$entry_background_color = rgba(08273111)
$entry_border_color = rgba(48526355)
$entry_color = rgba(FFFFFFFF)
$font_family = JetBrainsMono Nerd Font Medium
$font_family_clock = JetBrainsMono Nerd Font Medium
$font_material_symbols = JetBrainsMono Nerd Font Medium